/**
 * Everything the pages read from Sanity, shaped for the components. Queries live in ./queries.ts
 * and are typed by ../../sanity.types.ts (generated by `npm run typegen` in the Studio).
 *
 * Page copy may embed values from the site settings as `{{capacity}}`, `{{dateShort}}`, ... (the
 * list is in `varsOf`); they are replaced here, so pages never see the placeholders.
 */
import type { SanityImageSource } from '@sanity/image-url';
import type { Family } from '../data/site';
import type {
  ComingSoon as RawComingSoon,
  Cta as RawCta,
  Figure as RawFigure,
  Link as RawLink,
  PageHero as RawPageHero,
  Quote as RawQuote,
  Seo as RawSeo,
  Stat as RawStat,
  ACCOUNT_PAGE_QUERY_RESULT,
  VERIFY_PAGE_QUERY_RESULT,
  HOME_SPONSORS_QUERY_RESULT,
  SESSIONS_QUERY_RESULT,
  SPEAKERS_QUERY_RESULT,
} from '../../sanity.types';
import { sanityClient } from './client';
import { urlFor } from './image';
import {
  ABOUT_PAGE_QUERY,
  ACCOUNT_PAGE_QUERY,
  AGENDA_PAGE_QUERY,
  FAQ_PAGE_QUERY,
  FAQ_QUERY,
  HOME_PAGE_QUERY,
  HOME_SPONSORS_QUERY,
  ORGANIZERS_PAGE_QUERY,
  ORGANIZERS_QUERY,
  PRIVACY_PAGE_QUERY,
  SESSIONS_QUERY,
  SITE_SETTINGS_QUERY,
  SPEAKERS_PAGE_QUERY,
  SPEAKERS_QUERY,
  SPONSOR_TIERS_QUERY,
  SPONSORS_PAGE_QUERY,
  TRACKS_QUERY,
  VERIFY_PAGE_QUERY,
} from './queries';

const TBC = 'Speaker por confirmar';

/** "María José Vera" → "MV". Fallback when a person has no explicit initials. */
function initialsOf(name: string): string {
  const words = name.trim().split(/\s+/);
  const picked = words.length > 1 ? [words[0], words[words.length - 1]] : words;
  return picked
    .map((w) => w?.charAt(0) ?? '')
    .join('')
    .toUpperCase();
}

/* Placeholders --------------------------------------------------------------------------------- */

type Vars = Record<string, string | number>;

const PLACEHOLDER = /\{\{\s*(\w+)\s*\}\}/g;

function fill(text: string, vars: Vars): string {
  return text.replace(PLACEHOLDER, (match, key: string) =>
    key in vars ? String(vars[key]) : match,
  );
}

/** Replaces the placeholders in every string of a fetched document, however deep. */
function fillDeep<T>(value: T, vars: Vars): T {
  if (typeof value === 'string') return fill(value, vars) as T;
  if (Array.isArray(value)) return value.map((item) => fillDeep(item, vars)) as T;
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, fillDeep(item, vars)]),
    ) as T;
  }
  return value;
}

/* Shared shapes -------------------------------------------------------------------------------- */

export interface Link {
  label: string;
  href: string;
}

/** The register block that closes every page. */
export interface Cta {
  eyebrow: string;
  title: string;
  lead: string;
  primary: Link;
  secondary: Link;
}

/** Link preview image (Open Graph / X card), 1200×630. */
export interface ShareImage {
  src: string;
  alt: string;
  width: number;
  height: number;
}

export interface Seo {
  /** Page name, shown before " · DevFest Guayaquil 2026" unless it already contains it. */
  title: string;
  description: string;
  /** Overrides the site's default share image for this page. */
  image?: ShareImage;
}

export interface PageHero {
  eyebrow: string;
  title: string;
  lead: string;
  /** Glyph file names under /assets/glyphs, decoration only. */
  glyphs: string[];
}

export interface Stat {
  value: string;
  suffix?: string;
  label: string;
  /** Set when `value` is a whole number, for the count-up animation (`data-count`). */
  count?: number;
}

export interface Figure {
  src: string;
  alt: string;
  /** Chip in the corner of the photo. */
  tag?: string;
}

/** Replaces the hero's title and lead while a section is turned off in the site settings. */
export interface ComingSoon {
  title: string;
  lead: string;
  link?: Link;
}

export interface Quote {
  /** Bold opening word(s). */
  highlight?: string;
  text: string;
  attribution?: string;
}

const toLink = (l: RawLink): Link => ({ label: l.label, href: l.href });

type RawShareImage = NonNullable<RawSeo['image']>;

/** Fixed 1200×630 crop (honouring the hotspot) as JPEG: link scrapers do not all take WebP/AVIF. */
function toShareImage(image: RawShareImage | null | undefined): ShareImage | undefined {
  if (!image?.asset) return undefined;
  return {
    src: urlFor(image as SanityImageSource)
      .width(1200)
      .height(630)
      .fit('crop')
      .format('jpg')
      .quality(85)
      .url(),
    alt: image.alt ?? '',
    width: 1200,
    height: 630,
  };
}

const toSeo = (s: RawSeo): Seo => ({
  title: s.title,
  description: s.description,
  image: toShareImage(s.image),
});

const toPageHero = (h: RawPageHero): PageHero => ({
  eyebrow: h.eyebrow,
  title: h.title,
  lead: h.lead,
  glyphs: h.glyphs ?? [],
});

function toStat(s: RawStat): Stat {
  const value = s.value.trim();
  return {
    value,
    suffix: s.suffix ?? undefined,
    label: s.label,
    count: /^\d+$/.test(value) ? Number(value) : undefined,
  };
}

const toQuote = (q: RawQuote): Quote => ({
  highlight: q.highlight ?? undefined,
  text: q.text,
  attribution: q.attribution ?? undefined,
});

/** Square crop (the notch media is 1:1), honouring the hotspot set in the Studio. */
function toFigure(f: RawFigure): Figure | undefined {
  if (!f.image?.asset) return undefined;
  return {
    // The generated image type is structurally a SanityImageSource; the cast only bridges names.
    src: urlFor(f.image as SanityImageSource)
      .width(1000)
      .height(1000)
      .fit('crop')
      .auto('format')
      .url(),
    alt: f.image.alt ?? '',
    tag: f.tag ?? undefined,
  };
}

/* Site settings ------------------------------------------------------------------------------ */

export interface FooterColumn {
  heading: string;
  links: Link[];
}

export interface SiteSettings {
  name: string;
  year: number;
  /** "DevFest Guayaquil 2026", used in page titles. */
  title: string;
  /** ISO date, e.g. 2026-12-05 */
  date: string;
  /** "5 de diciembre, 2026" */
  dateShort: string;
  /** "5 de diciembre de 2026" */
  dateLong: string;
  venue: string;
  capacity: number;
  /** Registration form, or '#' while it does not exist yet. */
  registerHref: string;
  email: string;
  sponsorsEmail: string;
  communityUrl: string;
  /** communityUrl without protocol, e.g. gdg.community.dev/guayaquil */
  communityLabel: string;
  handle: string;
  /** Social profile, or '#' when not set. */
  socialHref: string;
  /** Default link preview image, from the Studio or the static fallback in /public. */
  shareImage: ShareImage;
  /** Who runs the event, e.g. "GDG Guayaquil" (the data controller's name, without its id). */
  organizer: string;
  /** Data controller under the LOPDP, e.g. "GDG Guayaquil" or "GDG Guayaquil (RUC …)". */
  controller: string;
  /** Where data-subject requests go; the contact email unless the Studio sets another. */
  privacyEmail: string;
  /** Sections turned on in the Studio; while one is off its page says "coming soon". */
  sections: { agenda: boolean; speakers: boolean; sponsors: boolean };
  /** Header menu, in order. */
  navigation: Link[];
  /** Default register block; a page can override parts of it. */
  registerCta: Cta;
  /** Replaces the header's register button once the visitor has signed in, e.g. "Mi cuenta". */
  accountLabel: string;
  footer: {
    columns: FooterColumn[];
    /** Heading of the column built from the community, social and email links. */
    followHeading: string;
    tagline: string;
  };
}

const DEFAULT_SHARE_IMAGE: ShareImage = {
  src: '/og-default.jpg',
  alt: 'DevFest 2026',
  width: 1200,
  height: 630,
};

function formatEventDate(iso: string) {
  const date = new Date(`${iso}T12:00:00Z`);
  const part = (options: Intl.DateTimeFormatOptions) =>
    new Intl.DateTimeFormat('es-EC', { timeZone: 'UTC', ...options }).format(date);
  const day = part({ day: 'numeric' });
  const month = part({ month: 'long' });
  const year = part({ year: 'numeric' });
  return { short: `${day} de ${month}, ${year}`, long: `${day} de ${month} de ${year}` };
}

type SiteVarsSource = Pick<
  SiteSettings,
  | 'name'
  | 'year'
  | 'title'
  | 'dateShort'
  | 'dateLong'
  | 'venue'
  | 'capacity'
  | 'email'
  | 'sponsorsEmail'
  | 'handle'
  | 'controller'
  | 'privacyEmail'
>;

/** The values `{{...}}` placeholders in page copy resolve to. */
const varsOf = (s: SiteVarsSource): Vars => ({
  name: s.name,
  year: s.year,
  title: s.title,
  dateShort: s.dateShort,
  dateLong: s.dateLong,
  venue: s.venue,
  capacity: s.capacity,
  email: s.email,
  sponsorsEmail: s.sponsorsEmail,
  handle: s.handle,
  controller: s.controller,
  privacyEmail: s.privacyEmail,
});

async function loadSiteSettings(): Promise<SiteSettings> {
  const s = await sanityClient.fetch(SITE_SETTINGS_QUERY);
  if (!s) {
    throw new Error(
      'No existe el documento "siteSettings" en Sanity. Ejecuta `npm run seed` en studio-gdg-gye-devfest o créalo desde el Studio.',
    );
  }
  if (!s.navigation || !s.registerCta || !s.footer) {
    throw new Error(
      'La configuración del sitio no tiene menú, bloque de registro o pie de página. Ejecuta `npm run seed:pages` en studio-gdg-gye-devfest o complétala desde el Studio.',
    );
  }
  const { short, long } = formatEventDate(s.date);
  const registerHref = s.registerUrl ?? '#';
  const base = {
    name: s.name,
    year: s.year,
    title: `${s.name} ${s.year}`,
    date: s.date,
    dateShort: short,
    dateLong: long,
    venue: s.venue,
    capacity: s.capacity,
    registerHref,
    email: s.email,
    sponsorsEmail: s.sponsorsEmail,
    communityUrl: s.communityUrl,
    communityLabel: s.communityUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''),
    handle: s.handle,
    socialHref: s.socialUrl ?? '#',
    shareImage: toShareImage(s.shareImage) ?? DEFAULT_SHARE_IMAGE,
    organizer: s.controllerName,
    controller: s.controllerId ? `${s.controllerName} (${s.controllerId})` : s.controllerName,
    privacyEmail: s.privacyEmail ?? s.email,
    sections: {
      agenda: s.showAgenda ?? false,
      speakers: s.showSpeakers ?? false,
      sponsors: s.showSponsors ?? false,
    },
  };
  const chrome = fillDeep(
    { navigation: s.navigation, registerCta: s.registerCta, footer: s.footer },
    varsOf(base),
  );
  return {
    ...base,
    navigation: chrome.navigation.map(toLink),
    registerCta: {
      eyebrow: chrome.registerCta.eyebrow,
      title: chrome.registerCta.title,
      lead: chrome.registerCta.lead,
      primary: { label: chrome.registerCta.primaryLabel, href: registerHref },
      secondary: toLink(chrome.registerCta.secondary),
    },
    accountLabel: chrome.registerCta.accountLabel,
    footer: {
      columns: chrome.footer.columns.map((c) => ({
        heading: c.heading,
        links: c.links.map(toLink),
      })),
      followHeading: chrome.footer.followHeading,
      tagline: chrome.footer.tagline,
    },
  };
}

let settingsPromise: Promise<SiteSettings> | undefined;

/** Fetched once per build. In dev every request re-fetches so Studio edits show up on reload. */
export function getSiteSettings(): Promise<SiteSettings> {
  if (import.meta.env.DEV || !settingsPromise) settingsPromise = loadSiteSettings();
  return settingsPromise;
}

/* Pages -------------------------------------------------------------------------------------- */

interface PageBase {
  seo: Seo;
  family: Family;
  /** Register block, with the page's overrides applied on top of the site default. */
  cta: Cta;
}

interface RawPageHead {
  seo: RawSeo;
  family: Family;
}

interface RawPageBase extends RawPageHead {
  cta: RawCta | null;
}

/** Fetches a page singleton, fails loudly when it is missing, and fills in the placeholders. */
async function loadPage<T extends RawPageHead>(
  id: string,
  fetchPage: () => Promise<T | null>,
): Promise<{ page: T; settings: SiteSettings }> {
  const [settings, raw] = await Promise.all([getSiteSettings(), fetchPage()]);
  if (!raw) {
    throw new Error(
      `No existe el documento "${id}" en Sanity. Ejecuta \`npm run seed:pages\` en studio-gdg-gye-devfest o créalo desde el Studio.`,
    );
  }
  return { page: fillDeep(raw, varsOf(settings)), settings };
}

/** A section page (agenda, speakers, sponsors) that can be switched off in the site settings. */
interface SectionPage {
  /** False while the section is off: show `comingSoon` instead of the content. */
  published: boolean;
  comingSoon: ComingSoon;
}

function sectionPage(
  id: string,
  published: boolean,
  raw: RawComingSoon | null | undefined,
): SectionPage {
  // Pages seeded before the switch existed have no copy for it; only needed while it is off.
  if (!raw && !published) {
    throw new Error(
      `La página "${id}" no tiene el texto "Próximamente". Ejecuta \`npm run seed:pages\` en studio-gdg-gye-devfest o complétalo desde el Studio.`,
    );
  }
  return {
    published,
    comingSoon: {
      title: raw?.title ?? '',
      lead: raw?.lead ?? '',
      link: raw?.link ? toLink(raw.link) : undefined,
    },
  };
}

function pageBase(p: RawPageBase, settings: SiteSettings): PageBase {
  const d = settings.registerCta;
  const o = p.cta;
  return {
    seo: toSeo(p.seo),
    family: p.family,
    cta: {
      eyebrow: o?.eyebrow ?? d.eyebrow,
      title: o?.title ?? d.title,
      lead: o?.lead ?? d.lead,
      primary: o?.primary ? toLink(o.primary) : d.primary,
      secondary: o?.secondary ? toLink(o.secondary) : d.secondary,
    },
  };
}

export interface HomePage extends PageBase {
  hero: {
    /** The first chip is tinted. */
    chips: string[];
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    figure?: Figure;
    glyphs: string[];
  };
  stats: Stat[];
  speakers: { eyebrow: string; title: string; lead: string; featured: SpeakerCard[]; link: Link };
  tracks: { eyebrow: string; title: string; linkLabel: string };
  quote: Quote;
  sponsors: { eyebrow: string; title: string; link: Link };
}

export async function getHomePage(): Promise<HomePage> {
  const { page: p, settings } = await loadPage('homePage', () =>
    sanityClient.fetch(HOME_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: {
      chips: p.hero.chips ?? [],
      title: p.hero.title,
      lead: p.hero.lead,
      primary: toLink(p.hero.primary),
      secondary: toLink(p.hero.secondary),
      figure: toFigure(p.hero.figure),
      glyphs: p.hero.glyphs ?? [],
    },
    stats: p.stats.map(toStat),
    speakers: {
      eyebrow: p.speakers.eyebrow,
      title: p.speakers.title,
      lead: p.speakers.lead,
      featured: (p.speakers.featured ?? []).map(toSpeakerCard),
      link: toLink(p.speakers.link),
    },
    tracks: {
      eyebrow: p.tracks.eyebrow,
      title: p.tracks.title,
      linkLabel: p.tracks.linkLabel,
    },
    quote: toQuote(p.quote),
    sponsors: {
      eyebrow: p.sponsors.eyebrow,
      title: p.sponsors.title,
      link: toLink(p.sponsors.link),
    },
  };
}

export interface AgendaPage extends PageBase, SectionPage {
  hero: PageHero;
  footnote: string;
}

export async function getAgendaPage(): Promise<AgendaPage> {
  const { page: p, settings } = await loadPage('agendaPage', () =>
    sanityClient.fetch(AGENDA_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    ...sectionPage('agendaPage', settings.sections.agenda, p.comingSoon),
    hero: toPageHero(p.hero),
    footnote: p.footnote,
  };
}

export interface SpeakersPage extends PageBase, SectionPage {
  hero: PageHero;
  cfp: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    note?: string;
    figure?: Figure;
  };
}

export async function getSpeakersPage(): Promise<SpeakersPage> {
  const { page: p, settings } = await loadPage('speakersPage', () =>
    sanityClient.fetch(SPEAKERS_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    ...sectionPage('speakersPage', settings.sections.speakers, p.comingSoon),
    hero: toPageHero(p.hero),
    cfp: {
      eyebrow: p.cfp.eyebrow,
      title: p.cfp.title,
      lead: p.cfp.lead,
      primary: toLink(p.cfp.primary),
      secondary: toLink(p.cfp.secondary),
      note: p.cfp.note ?? undefined,
      figure: toFigure(p.cfp.figure),
    },
  };
}

export interface SponsorsPage extends PageBase, SectionPage {
  hero: PageHero;
}

export async function getSponsorsPage(): Promise<SponsorsPage> {
  const { page: p, settings } = await loadPage('sponsorsPage', () =>
    sanityClient.fetch(SPONSORS_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    ...sectionPage('sponsorsPage', settings.sections.sponsors, p.comingSoon),
    hero: toPageHero(p.hero),
  };
}

export interface AboutPage extends PageBase {
  hero: PageHero;
  intro: { figure?: Figure; title: string; lead: string; body: string };
  principles: {
    eyebrow: string;
    title: string;
    items: { glyph: string; title: string; text: string }[];
  };
  history: {
    quote: Quote;
    stats: Stat[];
    eyebrow: string;
    title: string;
    /** Past events, one card each. */
    editions: { year: number; name: string; stats: Stat[] }[];
  };
  venue: { eyebrow: string; title: string; lead: string; link: Link; mapNote: string };
}

export async function getAboutPage(): Promise<AboutPage> {
  const { page: p, settings } = await loadPage('aboutPage', () =>
    sanityClient.fetch(ABOUT_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: toPageHero(p.hero),
    intro: {
      figure: toFigure(p.intro.figure),
      title: p.intro.title,
      lead: p.intro.lead,
      body: p.intro.body,
    },
    principles: {
      eyebrow: p.principles.eyebrow,
      title: p.principles.title,
      items: p.principles.items.map((i) => ({ glyph: i.glyph, title: i.title, text: i.text })),
    },
    history: {
      quote: toQuote(p.history.quote),
      stats: p.history.stats.map(toStat),
      // Older datasets lack these until `npm run seed:pages`; the section is hidden meanwhile.
      eyebrow: p.history.eyebrow ?? '',
      title: p.history.title ?? '',
      editions: (p.history.editions ?? []).map((e) => ({
        year: e.year,
        name: e.name,
        stats: e.stats.map(toStat),
      })),
    },
    venue: {
      eyebrow: p.venue.eyebrow,
      title: p.venue.title,
      lead: p.venue.lead,
      link: toLink(p.venue.link),
      mapNote: p.venue.mapNote,
    },
  };
}

export interface OrganizersPage extends PageBase {
  hero: PageHero;
  volunteering: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    stats: Stat[];
  };
}

export async function getOrganizersPage(): Promise<OrganizersPage> {
  const { page: p, settings } = await loadPage('organizersPage', () =>
    sanityClient.fetch(ORGANIZERS_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: toPageHero(p.hero),
    volunteering: {
      eyebrow: p.volunteering.eyebrow,
      title: p.volunteering.title,
      lead: p.volunteering.lead,
      primary: toLink(p.volunteering.primary),
      secondary: toLink(p.volunteering.secondary),
      stats: p.volunteering.stats.map(toStat),
    },
  };
}

export interface FaqPage extends PageBase {
  hero: PageHero;
}

export async function getFaqPage(): Promise<FaqPage> {
  const { page: p, settings } = await loadPage('faqPage', () => sanityClient.fetch(FAQ_PAGE_QUERY));
  return { ...pageBase(p, settings), hero: toPageHero(p.hero) };
}

/* Account, verification and privacy ---------------------------------------------------------- */

type AccountCopy = NonNullable<ACCOUNT_PAGE_QUERY_RESULT>;

export interface AccountPage {
  seo: Seo;
  family: Family;
  hero: PageHero;
  signIn: AccountCopy['signIn'];
  code: AccountCopy['code'];
  register: AccountCopy['register'];
  /** Short privacy notice shown before the registration form is sent. */
  notice: string[];
  /** One checkbox per purpose; the client hides those the database does not have active. */
  purposes: { key: string; label: string; description: string; required: boolean }[];
  dashboard: AccountCopy['dashboard'];
  privacy: AccountCopy['privacy'];
  reconsent: AccountCopy['reconsent'];
  errors: AccountCopy['errors'];
  staff: AccountCopy['staff'];
  /** Privacy notice version consents are recorded against (privacyPage.version). */
  policyVersion: string;
  /** This edition in the accounts database (public.events.slug): the site settings' year. */
  eventSlug: string;
}

/** Purposes an attendee cannot opt out of without deleting the account (public.purposes.required). */
const REQUIRED_PURPOSES = new Set(['account']);

export async function getAccountPage(): Promise<AccountPage> {
  const { page: p, settings } = await loadPage('accountPage', () =>
    sanityClient.fetch(ACCOUNT_PAGE_QUERY),
  );
  if (!p.policyVersion) {
    throw new Error(
      'No existe el documento "privacyPage" (Aviso de privacidad) o no tiene versión. Ejecuta `npm run seed:pages` en studio-gdg-gye-devfest o complétalo desde el Studio.',
    );
  }
  return {
    seo: toSeo(p.seo),
    family: p.family,
    hero: toPageHero(p.hero),
    signIn: p.signIn,
    code: p.code,
    register: p.register,
    notice: p.notice,
    purposes: p.purposes.map((purpose) => ({
      ...purpose,
      required: REQUIRED_PURPOSES.has(purpose.key),
    })),
    dashboard: p.dashboard,
    privacy: p.privacy,
    reconsent: p.reconsent,
    errors: p.errors,
    staff: p.staff,
    policyVersion: p.policyVersion,
    eventSlug: String(settings.year),
  };
}

type VerifyCopy = NonNullable<VERIFY_PAGE_QUERY_RESULT>;

export interface VerifyPage {
  seo: Seo;
  family: Family;
  hero: PageHero;
  form: VerifyCopy['form'];
  result: VerifyCopy['result'];
}

export async function getVerifyPage(): Promise<VerifyPage> {
  const { page: p } = await loadPage('verifyPage', () => sanityClient.fetch(VERIFY_PAGE_QUERY));
  return {
    seo: toSeo(p.seo),
    family: p.family,
    hero: toPageHero(p.hero),
    form: p.form,
    result: p.result,
  };
}

export interface PrivacyPage {
  seo: Seo;
  family: Family;
  hero: PageHero;
  version: string;
  /** "1 de octubre de 2026" */
  updatedAt: string;
  sections: { heading: string; paragraphs: string[] }[];
}

export async function getPrivacyPage(): Promise<PrivacyPage> {
  const { page: p } = await loadPage('privacyPage', () => sanityClient.fetch(PRIVACY_PAGE_QUERY));
  return {
    seo: toSeo(p.seo),
    family: p.family,
    hero: toPageHero(p.hero),
    version: p.version,
    updatedAt: formatEventDate(p.updatedAt).long,
    sections: p.sections.map((s) => ({
      heading: s.heading,
      paragraphs: s.body
        .split(/\n\s*\n/)
        .map((para) => para.trim())
        .filter(Boolean),
    })),
  };
}

/* Tracks ------------------------------------------------------------------------------------- */

export interface TrackCard {
  /** URL-safe id, used for the agenda tab and panel ids. */
  slug: string;
  name: string;
  family: Family;
  room: string;
  /** File name under /assets/glyphs, decoration only. */
  glyph: string;
  blurb: string;
}

export async function getTracks(): Promise<TrackCard[]> {
  const tracks = await sanityClient.fetch(TRACKS_QUERY);
  return tracks.map((t) => ({
    slug: t.slug ?? t._id,
    name: t.name,
    family: t.family,
    room: t.room,
    glyph: t.glyph,
    blurb: t.blurb,
  }));
}

/* Speakers ----------------------------------------------------------------------------------- */

export interface SpeakerCard {
  id: string;
  name: string;
  role: string;
  initials: string;
  family: Family;
  /** Track name, shown as the card chip. */
  track: string;
  /** Title of the speaker's session, once it is on the agenda. */
  talk?: string;
}

type RawSpeaker = SPEAKERS_QUERY_RESULT[number];

function toSpeakerCard(s: RawSpeaker): SpeakerCard {
  return {
    id: s._id,
    name: s.name,
    role: s.role,
    initials: s.initials ?? initialsOf(s.name),
    family: s.family,
    track: s.track.name,
    talk: s.talk ?? undefined,
  };
}

export async function getSpeakers(): Promise<SpeakerCard[]> {
  const speakers = await sanityClient.fetch(SPEAKERS_QUERY);
  return speakers.map(toSpeakerCard);
}

/* Agenda ------------------------------------------------------------------------------------- */

export interface Chip {
  label: string;
  /** chip modifier class (BEM), e.g. 'chip--tint' */
  cls?: string;
}

export interface Session {
  time: string;
  title: string;
  who?: string;
  chips?: Chip[];
  isBreak?: boolean;
}

export interface TrackSchedule {
  track: TrackCard;
  sessions: Session[];
}

type RawSession = SESSIONS_QUERY_RESULT[number];

function toSessionRow(s: RawSession): Session {
  const time = `${s.startTime} – ${s.endTime}`;
  const room = s.room ?? s.track?.room;
  // Plenary rows without a speaker line: breaks and the closing panel.
  if (s.kind === 'break' || s.kind === 'panel') {
    return { time, title: room ? `${s.title} · ${room}` : s.title, isBreak: true };
  }
  const chips: Chip[] = [];
  if (s.kind === 'keynote') chips.push({ label: 'Keynote', cls: 'chip--tint' });
  else if (s.track) chips.push({ label: s.track.name, cls: `chip--${s.track.family}` });
  if (room) chips.push({ label: room });
  return {
    time,
    title: s.title,
    who: s.speaker ? `${s.speaker.name} / ${s.speaker.role}` : TBC,
    chips,
  };
}

/** One tab per track: its own sessions plus the plenary ones (keynote, panel, breaks), by time. */
export async function getSchedule(): Promise<TrackSchedule[]> {
  const [tracks, sessions] = await Promise.all([getTracks(), sanityClient.fetch(SESSIONS_QUERY)]);
  return tracks.map((track) => ({
    track,
    sessions: sessions.filter((s) => !s.track || s.track.slug === track.slug).map(toSessionRow),
  }));
}

/** First start and last end on the agenda (HH:MM, venue time), or undefined while it is empty. */
export async function getEventHours(): Promise<{ start: string; end: string } | undefined> {
  const sessions = await sanityClient.fetch(SESSIONS_QUERY);
  if (!sessions.length) return undefined;
  // HH:MM is zero-padded (the Studio validates it), so string order is time order.
  const start = sessions.map((s) => s.startTime).reduce((a, b) => (b < a ? b : a));
  const end = sessions.map((s) => s.endTime).reduce((a, b) => (b > a ? b : a));
  return { start, end };
}

/* Organizers --------------------------------------------------------------------------------- */

export interface OrganizerCard {
  id: string;
  name: string;
  role: string;
  initials: string;
  /** Square crop of the Studio photo; without it the card shows the initials. */
  photo?: { src: string; alt: string };
  family: Family;
}

export async function getOrganizers(): Promise<OrganizerCard[]> {
  const organizers = await sanityClient.fetch(ORGANIZERS_QUERY);
  return organizers.map((o) => ({
    id: o._id,
    name: o.name,
    role: o.role,
    initials: o.initials ?? initialsOf(o.name),
    photo: o.photo?.asset
      ? {
          // The generated image type is structurally a SanityImageSource; the cast only bridges names.
          src: urlFor(o.photo as SanityImageSource)
            .width(600)
            .height(600)
            .fit('crop')
            .auto('format')
            .url(),
          alt: o.photo.alt ?? o.name,
        }
      : undefined,
    family: o.family,
  }));
}

/* Sponsors ----------------------------------------------------------------------------------- */

export interface SponsorTile {
  id: string;
  name: string;
  /** Sponsor site, or '#' when not set. */
  href: string;
  /** Present once a logo has been uploaded; the tile shows the name until then. */
  logo?: { src: string; alt: string };
}

export interface SponsorTierSection {
  id: string;
  name: string;
  kind: 'paid' | 'community';
  headline: string;
  description?: string;
  perks: string[];
  family: Family;
  sponsors: SponsorTile[];
}

type RawSponsor = HOME_SPONSORS_QUERY_RESULT[number];

function toSponsorTile(s: RawSponsor): SponsorTile {
  return {
    id: s._id,
    name: s.name,
    href: s.url ?? '#',
    logo: s.logo?.asset
      ? {
          // The generated image type is structurally a SanityImageSource; the cast only bridges names.
          src: urlFor(s.logo as SanityImageSource)
            .width(480)
            .height(240)
            .fit('max')
            .auto('format')
            .url(),
          alt: s.logo.alt ?? s.name,
        }
      : undefined,
  };
}

export async function getSponsorTiers(): Promise<SponsorTierSection[]> {
  const tiers = await sanityClient.fetch(SPONSOR_TIERS_QUERY);
  return tiers.map((t) => ({
    id: t._id,
    name: t.name,
    kind: t.kind,
    headline: t.headline,
    description: t.description ?? undefined,
    perks: t.perks ?? [],
    family: t.family,
    sponsors: t.sponsors.map(toSponsorTile),
  }));
}

/** Teaser tiles on the home page. */
export async function getHomeSponsors(): Promise<SponsorTile[]> {
  const sponsors = await sanityClient.fetch(HOME_SPONSORS_QUERY);
  return sponsors.map(toSponsorTile);
}

/* FAQ ---------------------------------------------------------------------------------------- */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  /** Anchor id; the code of conduct is linked from the footer as /faq#conducta. */
  anchor?: string;
}

export async function getFaq(): Promise<FaqItem[]> {
  const items = await sanityClient.fetch(FAQ_QUERY);
  return items.map((f) => ({
    id: f._id,
    question: f.question,
    answer: f.answer,
    anchor: f.anchor ?? undefined,
  }));
}
