/**
 * Everything the pages read from Sanity, shaped for the components. Queries live in ./queries.ts
 * and are typed by ../../sanity.types.ts (generated by `npm run typegen` in the Studio).
 */
import type { SanityImageSource } from '@sanity/image-url';
import type { Family } from '../data/site';
import type {
  HOME_SPONSORS_QUERY_RESULT,
  SESSIONS_QUERY_RESULT,
  SPEAKERS_QUERY_RESULT,
} from '../../sanity.types';
import { sanityClient } from './client';
import { urlFor } from './image';
import {
  FAQ_QUERY,
  HOME_SPONSORS_QUERY,
  ORGANIZERS_QUERY,
  SESSIONS_QUERY,
  SITE_SETTINGS_QUERY,
  SPEAKERS_QUERY,
  SPONSOR_TIERS_QUERY,
  TRACKS_QUERY,
} from './queries';

const TBC = 'Speaker por confirmar';

/** "María José Vera" → "MV". Fallback when a person has no explicit initials. */
function initialsOf(name: string): string {
  const words = name.trim().split(/\s+/);
  const picked = words.length > 1 ? [words[0], words[words.length - 1]] : words;
  return picked
    .map((w) => w?.charAt(0) ?? '')
    .join('')
    .toUpperCase();
}

/* Site settings ------------------------------------------------------------------------------ */

export interface SiteSettings {
  name: string;
  year: number;
  /** "DevFest Guayaquil 2026", used in page titles. */
  title: string;
  /** ISO date, e.g. 2026-12-05 */
  date: string;
  /** "5 de diciembre, 2026" */
  dateShort: string;
  /** "5 de diciembre de 2026" */
  dateLong: string;
  venue: string;
  capacity: number;
  /** Registration form, or '#' while it does not exist yet. */
  registerHref: string;
  email: string;
  sponsorsEmail: string;
  communityUrl: string;
  /** communityUrl without protocol, e.g. gdg.community.dev/guayaquil */
  communityLabel: string;
  handle: string;
  /** Social profile, or '#' when not set. */
  socialHref: string;
  featuredSpeakers: SpeakerCard[];
}

function formatEventDate(iso: string) {
  const date = new Date(`${iso}T12:00:00Z`);
  const part = (options: Intl.DateTimeFormatOptions) =>
    new Intl.DateTimeFormat('es-EC', { timeZone: 'UTC', ...options }).format(date);
  const day = part({ day: 'numeric' });
  const month = part({ month: 'long' });
  const year = part({ year: 'numeric' });
  return { short: `${day} de ${month}, ${year}`, long: `${day} de ${month} de ${year}` };
}

async function loadSiteSettings(): Promise<SiteSettings> {
  const s = await sanityClient.fetch(SITE_SETTINGS_QUERY);
  if (!s) {
    throw new Error(
      'No existe el documento "siteSettings" en Sanity. Ejecuta `npm run seed` en studio-gdg-gye-devfest o créalo desde el Studio.',
    );
  }
  const { short, long } = formatEventDate(s.date);
  return {
    name: s.name,
    year: s.year,
    title: `${s.name} ${s.year}`,
    date: s.date,
    dateShort: short,
    dateLong: long,
    venue: s.venue,
    capacity: s.capacity,
    registerHref: s.registerUrl ?? '#',
    email: s.email,
    sponsorsEmail: s.sponsorsEmail,
    communityUrl: s.communityUrl,
    communityLabel: s.communityUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''),
    handle: s.handle,
    socialHref: s.socialUrl ?? '#',
    featuredSpeakers: (s.featuredSpeakers ?? []).map(toSpeakerCard),
  };
}

let settingsPromise: Promise<SiteSettings> | undefined;

/** Fetched once per build. In dev every request re-fetches so Studio edits show up on reload. */
export function getSiteSettings(): Promise<SiteSettings> {
  if (import.meta.env.DEV || !settingsPromise) settingsPromise = loadSiteSettings();
  return settingsPromise;
}

/* Tracks ------------------------------------------------------------------------------------- */

export interface TrackCard {
  /** URL-safe id, used for the agenda tab and panel ids. */
  slug: string;
  name: string;
  family: Family;
  room: string;
  /** File name under /assets/glyphs, decoration only. */
  glyph: string;
  blurb: string;
}

export async function getTracks(): Promise<TrackCard[]> {
  const tracks = await sanityClient.fetch(TRACKS_QUERY);
  return tracks.map((t) => ({
    slug: t.slug ?? t._id,
    name: t.name,
    family: t.family,
    room: t.room,
    glyph: t.glyph,
    blurb: t.blurb,
  }));
}

/* Speakers ----------------------------------------------------------------------------------- */

export interface SpeakerCard {
  id: string;
  name: string;
  role: string;
  initials: string;
  family: Family;
  /** Track name, shown as the card chip. */
  track: string;
  /** Title of the speaker's session, once it is on the agenda. */
  talk?: string;
}

type RawSpeaker = SPEAKERS_QUERY_RESULT[number];

function toSpeakerCard(s: RawSpeaker): SpeakerCard {
  return {
    id: s._id,
    name: s.name,
    role: s.role,
    initials: s.initials ?? initialsOf(s.name),
    family: s.family,
    track: s.track.name,
    talk: s.talk ?? undefined,
  };
}

export async function getSpeakers(): Promise<SpeakerCard[]> {
  const speakers = await sanityClient.fetch(SPEAKERS_QUERY);
  return speakers.map(toSpeakerCard);
}

/* Agenda ------------------------------------------------------------------------------------- */

export interface Chip {
  label: string;
  /** chip modifier class (BEM), e.g. 'chip--tint' */
  cls?: string;
}

export interface Session {
  time: string;
  title: string;
  who?: string;
  chips?: Chip[];
  isBreak?: boolean;
}

export interface TrackSchedule {
  track: TrackCard;
  sessions: Session[];
}

type RawSession = SESSIONS_QUERY_RESULT[number];

function toSessionRow(s: RawSession): Session {
  const time = `${s.startTime} – ${s.endTime}`;
  const room = s.room ?? s.track?.room;
  // Plenary rows without a speaker line: breaks and the closing panel.
  if (s.kind === 'break' || s.kind === 'panel') {
    return { time, title: room ? `${s.title} · ${room}` : s.title, isBreak: true };
  }
  const chips: Chip[] = [];
  if (s.kind === 'keynote') chips.push({ label: 'Keynote', cls: 'chip--tint' });
  else if (s.track) chips.push({ label: s.track.name, cls: `chip--${s.track.family}` });
  if (room) chips.push({ label: room });
  return {
    time,
    title: s.title,
    who: s.speaker ? `${s.speaker.name} / ${s.speaker.role}` : TBC,
    chips,
  };
}

/** One tab per track: its own sessions plus the plenary ones (keynote, panel, breaks), by time. */
export async function getSchedule(): Promise<TrackSchedule[]> {
  const [tracks, sessions] = await Promise.all([getTracks(), sanityClient.fetch(SESSIONS_QUERY)]);
  return tracks.map((track) => ({
    track,
    sessions: sessions.filter((s) => !s.track || s.track.slug === track.slug).map(toSessionRow),
  }));
}

/* Organizers --------------------------------------------------------------------------------- */

export interface OrganizerCard {
  id: string;
  name: string;
  role: string;
  initials: string;
  family: Family;
}

export async function getOrganizers(): Promise<OrganizerCard[]> {
  const organizers = await sanityClient.fetch(ORGANIZERS_QUERY);
  return organizers.map((o) => ({
    id: o._id,
    name: o.name,
    role: o.role,
    initials: o.initials ?? initialsOf(o.name),
    family: o.family,
  }));
}

/* Sponsors ----------------------------------------------------------------------------------- */

export interface SponsorTile {
  id: string;
  name: string;
  /** Sponsor site, or '#' when not set. */
  href: string;
  /** Present once a logo has been uploaded; the tile shows the name until then. */
  logo?: { src: string; alt: string };
}

export interface SponsorTierSection {
  id: string;
  name: string;
  kind: 'paid' | 'community';
  headline: string;
  description?: string;
  perks: string[];
  family: Family;
  sponsors: SponsorTile[];
}

type RawSponsor = HOME_SPONSORS_QUERY_RESULT[number];

function toSponsorTile(s: RawSponsor): SponsorTile {
  return {
    id: s._id,
    name: s.name,
    href: s.url ?? '#',
    logo: s.logo?.asset
      ? {
          // The generated image type is structurally a SanityImageSource; the cast only bridges names.
          src: urlFor(s.logo as SanityImageSource)
            .width(480)
            .height(240)
            .fit('max')
            .auto('format')
            .url(),
          alt: s.logo.alt ?? s.name,
        }
      : undefined,
  };
}

export async function getSponsorTiers(): Promise<SponsorTierSection[]> {
  const tiers = await sanityClient.fetch(SPONSOR_TIERS_QUERY);
  return tiers.map((t) => ({
    id: t._id,
    name: t.name,
    kind: t.kind,
    headline: t.headline,
    description: t.description ?? undefined,
    perks: t.perks ?? [],
    family: t.family,
    sponsors: t.sponsors.map(toSponsorTile),
  }));
}

/** Teaser tiles on the home page. */
export async function getHomeSponsors(): Promise<SponsorTile[]> {
  const sponsors = await sanityClient.fetch(HOME_SPONSORS_QUERY);
  return sponsors.map(toSponsorTile);
}

/* FAQ ---------------------------------------------------------------------------------------- */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  /** Anchor id; the code of conduct is linked from the footer as /faq#conducta. */
  anchor?: string;
}

export async function getFaq(): Promise<FaqItem[]> {
  const items = await sanityClient.fetch(FAQ_QUERY);
  return items.map((f) => ({
    id: f._id,
    question: f.question,
    answer: f.answer,
    anchor: f.anchor ?? undefined,
  }));
}
