/**
 * Everything the pages read from Sanity, shaped for the components. Queries live in ./queries.ts
 * and are typed by ../../sanity.types.ts (generated by `npm run typegen` in the Studio).
 *
 * Page copy may embed values from the site settings as `{{capacity}}`, `{{dateShort}}`, ... (the
 * list is in `varsOf`); they are replaced here, so pages never see the placeholders.
 */
import type { SanityImageSource } from '@sanity/image-url';
import type { Family } from '../data/site';
import type {
  Cta as RawCta,
  Figure as RawFigure,
  Link as RawLink,
  PageHero as RawPageHero,
  Quote as RawQuote,
  Seo as RawSeo,
  Stat as RawStat,
  HOME_SPONSORS_QUERY_RESULT,
  SESSIONS_QUERY_RESULT,
  SPEAKERS_QUERY_RESULT,
} from '../../sanity.types';
import { sanityClient } from './client';
import { urlFor } from './image';
import {
  ABOUT_PAGE_QUERY,
  AGENDA_PAGE_QUERY,
  FAQ_PAGE_QUERY,
  FAQ_QUERY,
  HOME_PAGE_QUERY,
  HOME_SPONSORS_QUERY,
  ORGANIZERS_PAGE_QUERY,
  ORGANIZERS_QUERY,
  SESSIONS_QUERY,
  SITE_SETTINGS_QUERY,
  SPEAKERS_PAGE_QUERY,
  SPEAKERS_QUERY,
  SPONSOR_TIERS_QUERY,
  SPONSORS_PAGE_QUERY,
  TRACKS_QUERY,
} from './queries';

const TBC = 'Speaker por confirmar';

/** "María José Vera" → "MV". Fallback when a person has no explicit initials. */
function initialsOf(name: string): string {
  const words = name.trim().split(/\s+/);
  const picked = words.length > 1 ? [words[0], words[words.length - 1]] : words;
  return picked
    .map((w) => w?.charAt(0) ?? '')
    .join('')
    .toUpperCase();
}

/* Placeholders --------------------------------------------------------------------------------- */

type Vars = Record<string, string | number>;

const PLACEHOLDER = /\{\{\s*(\w+)\s*\}\}/g;

function fill(text: string, vars: Vars): string {
  return text.replace(PLACEHOLDER, (match, key: string) =>
    key in vars ? String(vars[key]) : match,
  );
}

/** Replaces the placeholders in every string of a fetched document, however deep. */
function fillDeep<T>(value: T, vars: Vars): T {
  if (typeof value === 'string') return fill(value, vars) as T;
  if (Array.isArray(value)) return value.map((item) => fillDeep(item, vars)) as T;
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, fillDeep(item, vars)]),
    ) as T;
  }
  return value;
}

/* Shared shapes -------------------------------------------------------------------------------- */

export interface Link {
  label: string;
  href: string;
}

/** The register block that closes every page. */
export interface Cta {
  eyebrow: string;
  title: string;
  lead: string;
  primary: Link;
  secondary: Link;
}

export interface Seo {
  /** Page name, shown before " · DevFest Guayaquil 2026". */
  title: string;
  description: string;
}

export interface PageHero {
  eyebrow: string;
  title: string;
  lead: string;
  /** Glyph file names under /assets/glyphs, decoration only. */
  glyphs: string[];
}

export interface Stat {
  value: string;
  suffix?: string;
  label: string;
  /** Set when `value` is a whole number, for the count-up animation (`data-count`). */
  count?: number;
}

export interface Figure {
  src: string;
  alt: string;
  /** Chip in the corner of the photo. */
  tag?: string;
}

export interface Quote {
  /** Bold opening word(s). */
  highlight?: string;
  text: string;
  attribution?: string;
}

const toLink = (l: RawLink): Link => ({ label: l.label, href: l.href });

const toSeo = (s: RawSeo): Seo => ({ title: s.title, description: s.description });

const toPageHero = (h: RawPageHero): PageHero => ({
  eyebrow: h.eyebrow,
  title: h.title,
  lead: h.lead,
  glyphs: h.glyphs ?? [],
});

function toStat(s: RawStat): Stat {
  const value = s.value.trim();
  return {
    value,
    suffix: s.suffix ?? undefined,
    label: s.label,
    count: /^\d+$/.test(value) ? Number(value) : undefined,
  };
}

const toQuote = (q: RawQuote): Quote => ({
  highlight: q.highlight ?? undefined,
  text: q.text,
  attribution: q.attribution ?? undefined,
});

/** Square crop (the notch media is 1:1), honouring the hotspot set in the Studio. */
function toFigure(f: RawFigure): Figure | undefined {
  if (!f.image?.asset) return undefined;
  return {
    // The generated image type is structurally a SanityImageSource; the cast only bridges names.
    src: urlFor(f.image as SanityImageSource)
      .width(1000)
      .height(1000)
      .fit('crop')
      .auto('format')
      .url(),
    alt: f.image.alt ?? '',
    tag: f.tag ?? undefined,
  };
}

/* Site settings ------------------------------------------------------------------------------ */

export interface FooterColumn {
  heading: string;
  links: Link[];
}

export interface SiteSettings {
  name: string;
  year: number;
  /** "DevFest Guayaquil 2026", used in page titles. */
  title: string;
  /** ISO date, e.g. 2026-12-05 */
  date: string;
  /** "5 de diciembre, 2026" */
  dateShort: string;
  /** "5 de diciembre de 2026" */
  dateLong: string;
  venue: string;
  capacity: number;
  /** Registration form, or '#' while it does not exist yet. */
  registerHref: string;
  email: string;
  sponsorsEmail: string;
  communityUrl: string;
  /** communityUrl without protocol, e.g. gdg.community.dev/guayaquil */
  communityLabel: string;
  handle: string;
  /** Social profile, or '#' when not set. */
  socialHref: string;
  /** Header menu, in order. */
  navigation: Link[];
  /** Default register block; a page can override parts of it. */
  registerCta: Cta;
  footer: {
    columns: FooterColumn[];
    /** Heading of the column built from the community, social and email links. */
    followHeading: string;
    tagline: string;
  };
}

function formatEventDate(iso: string) {
  const date = new Date(`${iso}T12:00:00Z`);
  const part = (options: Intl.DateTimeFormatOptions) =>
    new Intl.DateTimeFormat('es-EC', { timeZone: 'UTC', ...options }).format(date);
  const day = part({ day: 'numeric' });
  const month = part({ month: 'long' });
  const year = part({ year: 'numeric' });
  return { short: `${day} de ${month}, ${year}`, long: `${day} de ${month} de ${year}` };
}

type SiteVarsSource = Pick<
  SiteSettings,
  | 'name'
  | 'year'
  | 'title'
  | 'dateShort'
  | 'dateLong'
  | 'venue'
  | 'capacity'
  | 'email'
  | 'sponsorsEmail'
  | 'handle'
>;

/** The values `{{...}}` placeholders in page copy resolve to. */
const varsOf = (s: SiteVarsSource): Vars => ({
  name: s.name,
  year: s.year,
  title: s.title,
  dateShort: s.dateShort,
  dateLong: s.dateLong,
  venue: s.venue,
  capacity: s.capacity,
  email: s.email,
  sponsorsEmail: s.sponsorsEmail,
  handle: s.handle,
});

async function loadSiteSettings(): Promise<SiteSettings> {
  const s = await sanityClient.fetch(SITE_SETTINGS_QUERY);
  if (!s) {
    throw new Error(
      'No existe el documento "siteSettings" en Sanity. Ejecuta `npm run seed` en studio-gdg-gye-devfest o créalo desde el Studio.',
    );
  }
  if (!s.navigation || !s.registerCta || !s.footer) {
    throw new Error(
      'La configuración del sitio no tiene menú, bloque de registro o pie de página. Ejecuta `npm run seed:pages` en studio-gdg-gye-devfest o complétala desde el Studio.',
    );
  }
  const { short, long } = formatEventDate(s.date);
  const registerHref = s.registerUrl ?? '#';
  const base = {
    name: s.name,
    year: s.year,
    title: `${s.name} ${s.year}`,
    date: s.date,
    dateShort: short,
    dateLong: long,
    venue: s.venue,
    capacity: s.capacity,
    registerHref,
    email: s.email,
    sponsorsEmail: s.sponsorsEmail,
    communityUrl: s.communityUrl,
    communityLabel: s.communityUrl.replace(/^https?:\/\//, '').replace(/\/$/, ''),
    handle: s.handle,
    socialHref: s.socialUrl ?? '#',
  };
  const chrome = fillDeep(
    { navigation: s.navigation, registerCta: s.registerCta, footer: s.footer },
    varsOf(base),
  );
  return {
    ...base,
    navigation: chrome.navigation.map(toLink),
    registerCta: {
      eyebrow: chrome.registerCta.eyebrow,
      title: chrome.registerCta.title,
      lead: chrome.registerCta.lead,
      primary: { label: chrome.registerCta.primaryLabel, href: registerHref },
      secondary: toLink(chrome.registerCta.secondary),
    },
    footer: {
      columns: chrome.footer.columns.map((c) => ({
        heading: c.heading,
        links: c.links.map(toLink),
      })),
      followHeading: chrome.footer.followHeading,
      tagline: chrome.footer.tagline,
    },
  };
}

let settingsPromise: Promise<SiteSettings> | undefined;

/** Fetched once per build. In dev every request re-fetches so Studio edits show up on reload. */
export function getSiteSettings(): Promise<SiteSettings> {
  if (import.meta.env.DEV || !settingsPromise) settingsPromise = loadSiteSettings();
  return settingsPromise;
}

/* Pages -------------------------------------------------------------------------------------- */

interface PageBase {
  seo: Seo;
  family: Family;
  /** Register block, with the page's overrides applied on top of the site default. */
  cta: Cta;
}

interface RawPageBase {
  seo: RawSeo;
  family: Family;
  cta: RawCta | null;
}

/** Fetches a page singleton, fails loudly when it is missing, and fills in the placeholders. */
async function loadPage<T extends RawPageBase>(
  id: string,
  fetchPage: () => Promise<T | null>,
): Promise<{ page: T; settings: SiteSettings }> {
  const [settings, raw] = await Promise.all([getSiteSettings(), fetchPage()]);
  if (!raw) {
    throw new Error(
      `No existe el documento "${id}" en Sanity. Ejecuta \`npm run seed:pages\` en studio-gdg-gye-devfest o créalo desde el Studio.`,
    );
  }
  return { page: fillDeep(raw, varsOf(settings)), settings };
}

function pageBase(p: RawPageBase, settings: SiteSettings): PageBase {
  const d = settings.registerCta;
  const o = p.cta;
  return {
    seo: toSeo(p.seo),
    family: p.family,
    cta: {
      eyebrow: o?.eyebrow ?? d.eyebrow,
      title: o?.title ?? d.title,
      lead: o?.lead ?? d.lead,
      primary: o?.primary ? toLink(o.primary) : d.primary,
      secondary: o?.secondary ? toLink(o.secondary) : d.secondary,
    },
  };
}

export interface HomePage extends PageBase {
  hero: {
    /** The first chip is tinted. */
    chips: string[];
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    figure?: Figure;
    glyphs: string[];
  };
  stats: Stat[];
  speakers: { eyebrow: string; title: string; lead: string; featured: SpeakerCard[]; link: Link };
  tracks: { eyebrow: string; title: string; linkLabel: string };
  quote: Quote;
  sponsors: { eyebrow: string; title: string; link: Link };
}

export async function getHomePage(): Promise<HomePage> {
  const { page: p, settings } = await loadPage('homePage', () =>
    sanityClient.fetch(HOME_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: {
      chips: p.hero.chips ?? [],
      title: p.hero.title,
      lead: p.hero.lead,
      primary: toLink(p.hero.primary),
      secondary: toLink(p.hero.secondary),
      figure: toFigure(p.hero.figure),
      glyphs: p.hero.glyphs ?? [],
    },
    stats: p.stats.map(toStat),
    speakers: {
      eyebrow: p.speakers.eyebrow,
      title: p.speakers.title,
      lead: p.speakers.lead,
      featured: (p.speakers.featured ?? []).map(toSpeakerCard),
      link: toLink(p.speakers.link),
    },
    tracks: {
      eyebrow: p.tracks.eyebrow,
      title: p.tracks.title,
      linkLabel: p.tracks.linkLabel,
    },
    quote: toQuote(p.quote),
    sponsors: {
      eyebrow: p.sponsors.eyebrow,
      title: p.sponsors.title,
      link: toLink(p.sponsors.link),
    },
  };
}

export interface AgendaPage extends PageBase {
  hero: PageHero;
  footnote: string;
}

export async function getAgendaPage(): Promise<AgendaPage> {
  const { page: p, settings } = await loadPage('agendaPage', () =>
    sanityClient.fetch(AGENDA_PAGE_QUERY),
  );
  return { ...pageBase(p, settings), hero: toPageHero(p.hero), footnote: p.footnote };
}

export interface SpeakersPage extends PageBase {
  hero: PageHero;
  cfp: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    note?: string;
    figure?: Figure;
  };
}

export async function getSpeakersPage(): Promise<SpeakersPage> {
  const { page: p, settings } = await loadPage('speakersPage', () =>
    sanityClient.fetch(SPEAKERS_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: toPageHero(p.hero),
    cfp: {
      eyebrow: p.cfp.eyebrow,
      title: p.cfp.title,
      lead: p.cfp.lead,
      primary: toLink(p.cfp.primary),
      secondary: toLink(p.cfp.secondary),
      note: p.cfp.note ?? undefined,
      figure: toFigure(p.cfp.figure),
    },
  };
}

export interface SponsorsPage extends PageBase {
  hero: PageHero;
}

export async function getSponsorsPage(): Promise<SponsorsPage> {
  const { page: p, settings } = await loadPage('sponsorsPage', () =>
    sanityClient.fetch(SPONSORS_PAGE_QUERY),
  );
  return { ...pageBase(p, settings), hero: toPageHero(p.hero) };
}

export interface AboutPage extends PageBase {
  hero: PageHero;
  intro: { figure?: Figure; title: string; lead: string; body: string };
  principles: {
    eyebrow: string;
    title: string;
    items: { glyph: string; title: string; text: string }[];
  };
  history: { quote: Quote; stats: Stat[] };
  venue: { eyebrow: string; title: string; lead: string; link: Link; mapNote: string };
}

export async function getAboutPage(): Promise<AboutPage> {
  const { page: p, settings } = await loadPage('aboutPage', () =>
    sanityClient.fetch(ABOUT_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: toPageHero(p.hero),
    intro: {
      figure: toFigure(p.intro.figure),
      title: p.intro.title,
      lead: p.intro.lead,
      body: p.intro.body,
    },
    principles: {
      eyebrow: p.principles.eyebrow,
      title: p.principles.title,
      items: p.principles.items.map((i) => ({ glyph: i.glyph, title: i.title, text: i.text })),
    },
    history: { quote: toQuote(p.history.quote), stats: p.history.stats.map(toStat) },
    venue: {
      eyebrow: p.venue.eyebrow,
      title: p.venue.title,
      lead: p.venue.lead,
      link: toLink(p.venue.link),
      mapNote: p.venue.mapNote,
    },
  };
}

export interface OrganizersPage extends PageBase {
  hero: PageHero;
  volunteering: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    stats: Stat[];
  };
}

export async function getOrganizersPage(): Promise<OrganizersPage> {
  const { page: p, settings } = await loadPage('organizersPage', () =>
    sanityClient.fetch(ORGANIZERS_PAGE_QUERY),
  );
  return {
    ...pageBase(p, settings),
    hero: toPageHero(p.hero),
    volunteering: {
      eyebrow: p.volunteering.eyebrow,
      title: p.volunteering.title,
      lead: p.volunteering.lead,
      primary: toLink(p.volunteering.primary),
      secondary: toLink(p.volunteering.secondary),
      stats: p.volunteering.stats.map(toStat),
    },
  };
}

export interface FaqPage extends PageBase {
  hero: PageHero;
}

export async function getFaqPage(): Promise<FaqPage> {
  const { page: p, settings } = await loadPage('faqPage', () => sanityClient.fetch(FAQ_PAGE_QUERY));
  return { ...pageBase(p, settings), hero: toPageHero(p.hero) };
}

/* Tracks ------------------------------------------------------------------------------------- */

export interface TrackCard {
  /** URL-safe id, used for the agenda tab and panel ids. */
  slug: string;
  name: string;
  family: Family;
  room: string;
  /** File name under /assets/glyphs, decoration only. */
  glyph: string;
  blurb: string;
}

export async function getTracks(): Promise<TrackCard[]> {
  const tracks = await sanityClient.fetch(TRACKS_QUERY);
  return tracks.map((t) => ({
    slug: t.slug ?? t._id,
    name: t.name,
    family: t.family,
    room: t.room,
    glyph: t.glyph,
    blurb: t.blurb,
  }));
}

/* Speakers ----------------------------------------------------------------------------------- */

export interface SpeakerCard {
  id: string;
  name: string;
  role: string;
  initials: string;
  family: Family;
  /** Track name, shown as the card chip. */
  track: string;
  /** Title of the speaker's session, once it is on the agenda. */
  talk?: string;
}

type RawSpeaker = SPEAKERS_QUERY_RESULT[number];

function toSpeakerCard(s: RawSpeaker): SpeakerCard {
  return {
    id: s._id,
    name: s.name,
    role: s.role,
    initials: s.initials ?? initialsOf(s.name),
    family: s.family,
    track: s.track.name,
    talk: s.talk ?? undefined,
  };
}

export async function getSpeakers(): Promise<SpeakerCard[]> {
  const speakers = await sanityClient.fetch(SPEAKERS_QUERY);
  return speakers.map(toSpeakerCard);
}

/* Agenda ------------------------------------------------------------------------------------- */

export interface Chip {
  label: string;
  /** chip modifier class (BEM), e.g. 'chip--tint' */
  cls?: string;
}

export interface Session {
  time: string;
  title: string;
  who?: string;
  chips?: Chip[];
  isBreak?: boolean;
}

export interface TrackSchedule {
  track: TrackCard;
  sessions: Session[];
}

type RawSession = SESSIONS_QUERY_RESULT[number];

function toSessionRow(s: RawSession): Session {
  const time = `${s.startTime} – ${s.endTime}`;
  const room = s.room ?? s.track?.room;
  // Plenary rows without a speaker line: breaks and the closing panel.
  if (s.kind === 'break' || s.kind === 'panel') {
    return { time, title: room ? `${s.title} · ${room}` : s.title, isBreak: true };
  }
  const chips: Chip[] = [];
  if (s.kind === 'keynote') chips.push({ label: 'Keynote', cls: 'chip--tint' });
  else if (s.track) chips.push({ label: s.track.name, cls: `chip--${s.track.family}` });
  if (room) chips.push({ label: room });
  return {
    time,
    title: s.title,
    who: s.speaker ? `${s.speaker.name} / ${s.speaker.role}` : TBC,
    chips,
  };
}

/** One tab per track: its own sessions plus the plenary ones (keynote, panel, breaks), by time. */
export async function getSchedule(): Promise<TrackSchedule[]> {
  const [tracks, sessions] = await Promise.all([getTracks(), sanityClient.fetch(SESSIONS_QUERY)]);
  return tracks.map((track) => ({
    track,
    sessions: sessions.filter((s) => !s.track || s.track.slug === track.slug).map(toSessionRow),
  }));
}

/* Organizers --------------------------------------------------------------------------------- */

export interface OrganizerCard {
  id: string;
  name: string;
  role: string;
  initials: string;
  family: Family;
}

export async function getOrganizers(): Promise<OrganizerCard[]> {
  const organizers = await sanityClient.fetch(ORGANIZERS_QUERY);
  return organizers.map((o) => ({
    id: o._id,
    name: o.name,
    role: o.role,
    initials: o.initials ?? initialsOf(o.name),
    family: o.family,
  }));
}

/* Sponsors ----------------------------------------------------------------------------------- */

export interface SponsorTile {
  id: string;
  name: string;
  /** Sponsor site, or '#' when not set. */
  href: string;
  /** Present once a logo has been uploaded; the tile shows the name until then. */
  logo?: { src: string; alt: string };
}

export interface SponsorTierSection {
  id: string;
  name: string;
  kind: 'paid' | 'community';
  headline: string;
  description?: string;
  perks: string[];
  family: Family;
  sponsors: SponsorTile[];
}

type RawSponsor = HOME_SPONSORS_QUERY_RESULT[number];

function toSponsorTile(s: RawSponsor): SponsorTile {
  return {
    id: s._id,
    name: s.name,
    href: s.url ?? '#',
    logo: s.logo?.asset
      ? {
          // The generated image type is structurally a SanityImageSource; the cast only bridges names.
          src: urlFor(s.logo as SanityImageSource)
            .width(480)
            .height(240)
            .fit('max')
            .auto('format')
            .url(),
          alt: s.logo.alt ?? s.name,
        }
      : undefined,
  };
}

export async function getSponsorTiers(): Promise<SponsorTierSection[]> {
  const tiers = await sanityClient.fetch(SPONSOR_TIERS_QUERY);
  return tiers.map((t) => ({
    id: t._id,
    name: t.name,
    kind: t.kind,
    headline: t.headline,
    description: t.description ?? undefined,
    perks: t.perks ?? [],
    family: t.family,
    sponsors: t.sponsors.map(toSponsorTile),
  }));
}

/** Teaser tiles on the home page. */
export async function getHomeSponsors(): Promise<SponsorTile[]> {
  const sponsors = await sanityClient.fetch(HOME_SPONSORS_QUERY);
  return sponsors.map(toSponsorTile);
}

/* FAQ ---------------------------------------------------------------------------------------- */

export interface FaqItem {
  id: string;
  question: string;
  answer: string;
  /** Anchor id; the code of conduct is linked from the footer as /faq#conducta. */
  anchor?: string;
}

export async function getFaq(): Promise<FaqItem[]> {
  const items = await sanityClient.fetch(FAQ_QUERY);
  return items.map((f) => ({
    id: f._id,
    question: f.question,
    answer: f.answer,
    anchor: f.anchor ?? undefined,
  }));
}
