/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  anchor?: Slug;
  order?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SponsorTierReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sponsorTier";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Sponsor = {
  _id: string;
  _type: "sponsor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  tier: SponsorTierReference;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  url?: string;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SponsorTier = {
  _id: string;
  _type: "sponsorTier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  kind: "paid" | "community";
  headline: string;
  description?: string;
  perks?: Array<string>;
  family: "yellow" | "blue" | "green" | "red";
  order?: number;
};

export type Organizer = {
  _id: string;
  _type: "organizer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  initials?: string;
  family: "yellow" | "blue" | "green" | "red";
  order?: number;
};

export type TrackReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "track";
};

export type SpeakerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "speaker";
};

export type Session = {
  _id: string;
  _type: "session";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  kind: "talk" | "workshop" | "keynote" | "panel" | "break";
  startTime: string;
  endTime: string;
  track?: TrackReference;
  speaker?: SpeakerReference;
  room?: string;
  order?: number;
};

export type Speaker = {
  _id: string;
  _type: "speaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: string;
  initials?: string;
  track: TrackReference;
  family: "yellow" | "blue" | "green" | "red";
  order?: number;
};

export type Track = {
  _id: string;
  _type: "track";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  blurb: string;
  room: string;
  glyph: "braces" | "semicolon" | "globe" | "at" | "asterisk" | "heart" | "hash-green" | "slash-a" | "x-pink" | "comma-yellow" | "plus-blue" | "half-circle-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "brace-left" | "brace-right" | "arrow-right" | "quote-open";
  family: "yellow" | "blue" | "green" | "red";
  order?: number;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: PageHero;
  cta?: Cta;
};

export type Cta = {
  _type: "cta";
  eyebrow?: string;
  title?: string;
  lead?: string;
  primary?: Link;
  secondary?: Link;
};

export type PageHero = {
  _type: "pageHero";
  eyebrow: string;
  title: string;
  lead: string;
  glyphs?: Array<"braces" | "semicolon" | "globe" | "at" | "asterisk" | "heart" | "hash-green" | "slash-a" | "x-pink" | "comma-yellow" | "plus-blue" | "half-circle-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "brace-left" | "brace-right" | "arrow-right" | "quote-open">;
};

export type Seo = {
  _type: "seo";
  title: string;
  description: string;
};

export type OrganizersPage = {
  _id: string;
  _type: "organizersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: PageHero;
  volunteering: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    stats: Array<{
      _key: string;
    } & Stat>;
  };
  cta?: Cta;
};

export type Link = {
  _type: "link";
  label: string;
  href: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: PageHero;
  intro: {
    figure: Figure;
    title: string;
    lead: string;
    body: string;
  };
  principles: {
    eyebrow: string;
    title: string;
    items: Array<{
      glyph: "braces" | "semicolon" | "globe" | "at" | "asterisk" | "heart" | "hash-green" | "slash-a" | "x-pink" | "comma-yellow" | "plus-blue" | "half-circle-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "brace-left" | "brace-right" | "arrow-right" | "quote-open";
      title: string;
      text: string;
      _type: "principle";
      _key: string;
    }>;
  };
  history: {
    quote: Quote;
    stats: Array<{
      _key: string;
    } & Stat>;
  };
  venue: {
    eyebrow: string;
    title: string;
    lead: string;
    link: Link;
    mapNote: string;
  };
  cta?: Cta;
};

export type Quote = {
  _type: "quote";
  highlight?: string;
  text: string;
  attribution?: string;
};

export type Figure = {
  _type: "figure";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  tag?: string;
};

export type SponsorsPage = {
  _id: string;
  _type: "sponsorsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: PageHero;
  cta?: Cta;
};

export type SpeakersPage = {
  _id: string;
  _type: "speakersPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: PageHero;
  cfp: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    note?: string;
    figure: Figure;
  };
  cta?: Cta;
};

export type AgendaPage = {
  _id: string;
  _type: "agendaPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: PageHero;
  footnote: string;
  cta?: Cta;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: Seo;
  family: "yellow" | "blue" | "green" | "red";
  hero: {
    chips?: Array<string>;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    figure: Figure;
    glyphs?: Array<"braces" | "semicolon" | "globe" | "at" | "asterisk" | "heart" | "hash-green" | "slash-a" | "x-pink" | "comma-yellow" | "plus-blue" | "half-circle-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "brace-left" | "brace-right" | "arrow-right" | "quote-open">;
  };
  stats: Array<{
    _key: string;
  } & Stat>;
  speakers: {
    eyebrow: string;
    title: string;
    lead: string;
    featured?: Array<{
      _key: string;
    } & SpeakerReference>;
    link: Link;
  };
  tracks: {
    eyebrow: string;
    title: string;
    linkLabel: string;
  };
  quote: Quote;
  sponsors: {
    eyebrow: string;
    title: string;
    link: Link;
  };
  cta?: Cta;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  year: number;
  date: string;
  venue: string;
  capacity: number;
  registerUrl?: string;
  email: string;
  sponsorsEmail: string;
  communityUrl: string;
  handle: string;
  socialUrl?: string;
  navigation: Array<{
    _key: string;
  } & Link>;
  registerCta: {
    eyebrow: string;
    title: string;
    lead: string;
    primaryLabel: string;
    secondary: Link;
  };
  footer: {
    columns: Array<{
      heading: string;
      links: Array<{
        _key: string;
      } & Link>;
      _type: "footerColumn";
      _key: string;
    }>;
    followHeading: string;
    tagline: string;
  };
};

export type Stat = {
  _type: "stat";
  value: string;
  suffix?: string;
  label: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Faq | Slug | SponsorTierReference | SanityImageAssetReference | Sponsor | SanityImageCrop | SanityImageHotspot | SponsorTier | Organizer | TrackReference | SpeakerReference | Session | Speaker | Track | FaqPage | Cta | PageHero | Seo | OrganizersPage | Link | AboutPage | Quote | Figure | SponsorsPage | SpeakersPage | AgendaPage | HomePage | SiteSettings | Stat | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    year,    date,    venue,    capacity,    registerUrl,    email,    sponsorsEmail,    communityUrl,    handle,    socialUrl,    navigation,    registerCta,    footer  }
export type SITE_SETTINGS_QUERY_RESULT = {
  name: string;
  year: number;
  date: string;
  venue: string;
  capacity: number;
  registerUrl: string | null;
  email: string;
  sponsorsEmail: string;
  communityUrl: string;
  handle: string;
  socialUrl: string | null;
  navigation: Array<{
    _key: string;
  } & Link>;
  registerCta: {
    eyebrow: string;
    title: string;
    lead: string;
    primaryLabel: string;
    secondary: Link;
  };
  footer: {
    columns: Array<{
      heading: string;
      links: Array<{
        _key: string;
      } & Link>;
      _type: "footerColumn";
      _key: string;
    }>;
    followHeading: string;
    tagline: string;
  };
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage" && _id == "homePage"][0]{    seo,    family,    hero,    stats,    speakers{      eyebrow,      title,      lead,      link,      featured[]->{   _id,  name,  role,  initials,  family,  track->{   name,  "slug": slug.current,  room,  family },  "talk": *[_type == "session" && speaker._ref == ^._id] | order(startTime asc)[0].title }    },    tracks,    quote,    sponsors,    cta  }
export type HOME_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: {
    chips?: Array<string>;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    figure: Figure;
    glyphs?: Array<"arrow-right" | "asterisk" | "at" | "brace-left" | "brace-right" | "braces" | "comma-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "globe" | "half-circle-yellow" | "hash-green" | "heart" | "plus-blue" | "quote-open" | "semicolon" | "slash-a" | "x-pink">;
  };
  stats: Array<{
    _key: string;
  } & Stat>;
  speakers: {
    eyebrow: string;
    title: string;
    lead: string;
    link: Link;
    featured: Array<{
      _id: string;
      name: string;
      role: string;
      initials: string | null;
      family: "blue" | "green" | "red" | "yellow";
      track: {
        name: string;
        slug: string;
        room: string;
        family: "blue" | "green" | "red" | "yellow";
      };
      talk: string | null;
    }> | null;
  };
  tracks: {
    eyebrow: string;
    title: string;
    linkLabel: string;
  };
  quote: Quote;
  sponsors: {
    eyebrow: string;
    title: string;
    link: Link;
  };
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: AGENDA_PAGE_QUERY
// Query: *[_type == "agendaPage" && _id == "agendaPage"][0]{ seo, family, hero, footnote, cta }
export type AGENDA_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: PageHero;
  footnote: string;
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: SPEAKERS_PAGE_QUERY
// Query: *[_type == "speakersPage" && _id == "speakersPage"][0]{ seo, family, hero, cfp, cta }
export type SPEAKERS_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: PageHero;
  cfp: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    note?: string;
    figure: Figure;
  };
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: SPONSORS_PAGE_QUERY
// Query: *[_type == "sponsorsPage" && _id == "sponsorsPage"][0]{ seo, family, hero, cta }
export type SPONSORS_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: PageHero;
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: ABOUT_PAGE_QUERY
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    seo,    family,    hero,    intro,    principles,    history,    venue,    cta  }
export type ABOUT_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: PageHero;
  intro: {
    figure: Figure;
    title: string;
    lead: string;
    body: string;
  };
  principles: {
    eyebrow: string;
    title: string;
    items: Array<{
      glyph: "arrow-right" | "asterisk" | "at" | "brace-left" | "brace-right" | "braces" | "comma-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "globe" | "half-circle-yellow" | "hash-green" | "heart" | "plus-blue" | "quote-open" | "semicolon" | "slash-a" | "x-pink";
      title: string;
      text: string;
      _type: "principle";
      _key: string;
    }>;
  };
  history: {
    quote: Quote;
    stats: Array<{
      _key: string;
    } & Stat>;
  };
  venue: {
    eyebrow: string;
    title: string;
    lead: string;
    link: Link;
    mapNote: string;
  };
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: ORGANIZERS_PAGE_QUERY
// Query: *[_type == "organizersPage" && _id == "organizersPage"][0]{ seo, family, hero, volunteering, cta }
export type ORGANIZERS_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: PageHero;
  volunteering: {
    eyebrow: string;
    title: string;
    lead: string;
    primary: Link;
    secondary: Link;
    stats: Array<{
      _key: string;
    } & Stat>;
  };
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: FAQ_PAGE_QUERY
// Query: *[_type == "faqPage" && _id == "faqPage"][0]{ seo, family, hero, cta }
export type FAQ_PAGE_QUERY_RESULT = {
  seo: Seo;
  family: "blue" | "green" | "red" | "yellow";
  hero: PageHero;
  cta: Cta | null;
} | null;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: TRACKS_QUERY
// Query: *[_type == "track"] | order(coalesce(order, 9999) asc, name asc){    _id,      name,  "slug": slug.current,  room,  family,    glyph,    blurb  }
export type TRACKS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  room: string;
  family: "blue" | "green" | "red" | "yellow";
  glyph: "arrow-right" | "asterisk" | "at" | "brace-left" | "brace-right" | "braces" | "comma-yellow" | "dot-blue" | "dot-green" | "dot-red" | "dot-yellow" | "globe" | "half-circle-yellow" | "hash-green" | "heart" | "plus-blue" | "quote-open" | "semicolon" | "slash-a" | "x-pink";
  blurb: string;
}>;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: SPEAKERS_QUERY
// Query: *[_type == "speaker"] | order(coalesce(order, 9999) asc, name asc){   _id,  name,  role,  initials,  family,  track->{   name,  "slug": slug.current,  room,  family },  "talk": *[_type == "session" && speaker._ref == ^._id] | order(startTime asc)[0].title }
export type SPEAKERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  initials: string | null;
  family: "blue" | "green" | "red" | "yellow";
  track: {
    name: string;
    slug: string;
    room: string;
    family: "blue" | "green" | "red" | "yellow";
  };
  talk: string | null;
}>;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: SESSIONS_QUERY
// Query: *[_type == "session"] | order(startTime asc, coalesce(order, 9999) asc, title asc){    _id,    title,    kind,    startTime,    endTime,    room,    track->{   name,  "slug": slug.current,  room,  family },    speaker->{ name, role }  }
export type SESSIONS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  kind: "break" | "keynote" | "panel" | "talk" | "workshop";
  startTime: string;
  endTime: string;
  room: string | null;
  track: {
    name: string;
    slug: string;
    room: string;
    family: "blue" | "green" | "red" | "yellow";
  } | null;
  speaker: {
    name: string;
    role: string;
  } | null;
}>;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: ORGANIZERS_QUERY
// Query: *[_type == "organizer"] | order(coalesce(order, 9999) asc, name asc){    _id,    name,    role,    initials,    family  }
export type ORGANIZERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  role: string;
  initials: string | null;
  family: "blue" | "green" | "red" | "yellow";
}>;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: SPONSOR_TIERS_QUERY
// Query: *[_type == "sponsorTier"] | order(coalesce(order, 9999) asc, name asc){    _id,    name,    kind,    headline,    description,    perks,    family,    "sponsors": *[_type == "sponsor" && tier._ref == ^._id]      | order(coalesce(order, 9999) asc, name asc){   _id,  name,  url,  logo }  }
export type SPONSOR_TIERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  kind: "community" | "paid";
  headline: string;
  description: string | null;
  perks: Array<string> | null;
  family: "blue" | "green" | "red" | "yellow";
  sponsors: Array<{
    _id: string;
    name: string;
    url: string | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  }>;
}>;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: HOME_SPONSORS_QUERY
// Query: *[_type == "sponsor" && tier._ref in *[_type == "sponsorTier" && kind == "paid"]._id]    | order(tier->order asc, coalesce(order, 9999) asc, name asc)[0...4]{   _id,  name,  url,  logo }
export type HOME_SPONSORS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  url: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: ../gdg-gye-devfest-fe/src/sanity/queries.ts
// Variable: FAQ_QUERY
// Query: *[_type == "faq"] | order(coalesce(order, 9999) asc){    _id,    question,    answer,    "anchor": anchor.current  }
export type FAQ_QUERY_RESULT = Array<{
  _id: string;
  question: string;
  answer: string;
  anchor: string | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    "\n  *[_type == \"siteSettings\" && _id == \"siteSettings\"][0]{\n    name,\n    year,\n    date,\n    venue,\n    capacity,\n    registerUrl,\n    email,\n    sponsorsEmail,\n    communityUrl,\n    handle,\n    socialUrl,\n    navigation,\n    registerCta,\n    footer\n  }\n": SITE_SETTINGS_QUERY_RESULT;
    "\n  *[_type == \"homePage\" && _id == \"homePage\"][0]{\n    seo,\n    family,\n    hero,\n    stats,\n    speakers{\n      eyebrow,\n      title,\n      lead,\n      link,\n      featured[]->{ \n  _id,\n  name,\n  role,\n  initials,\n  family,\n  track->{ \n  name,\n  \"slug\": slug.current,\n  room,\n  family\n },\n  \"talk\": *[_type == \"session\" && speaker._ref == ^._id] | order(startTime asc)[0].title\n }\n    },\n    tracks,\n    quote,\n    sponsors,\n    cta\n  }\n": HOME_PAGE_QUERY_RESULT;
    "\n  *[_type == \"agendaPage\" && _id == \"agendaPage\"][0]{ seo, family, hero, footnote, cta }\n": AGENDA_PAGE_QUERY_RESULT;
    "\n  *[_type == \"speakersPage\" && _id == \"speakersPage\"][0]{ seo, family, hero, cfp, cta }\n": SPEAKERS_PAGE_QUERY_RESULT;
    "\n  *[_type == \"sponsorsPage\" && _id == \"sponsorsPage\"][0]{ seo, family, hero, cta }\n": SPONSORS_PAGE_QUERY_RESULT;
    "\n  *[_type == \"aboutPage\" && _id == \"aboutPage\"][0]{\n    seo,\n    family,\n    hero,\n    intro,\n    principles,\n    history,\n    venue,\n    cta\n  }\n": ABOUT_PAGE_QUERY_RESULT;
    "\n  *[_type == \"organizersPage\" && _id == \"organizersPage\"][0]{ seo, family, hero, volunteering, cta }\n": ORGANIZERS_PAGE_QUERY_RESULT;
    "\n  *[_type == \"faqPage\" && _id == \"faqPage\"][0]{ seo, family, hero, cta }\n": FAQ_PAGE_QUERY_RESULT;
    "\n  *[_type == \"track\"] | order(coalesce(order, 9999) asc, name asc){\n    _id,\n    \n  name,\n  \"slug\": slug.current,\n  room,\n  family\n,\n    glyph,\n    blurb\n  }\n": TRACKS_QUERY_RESULT;
    "\n  *[_type == \"speaker\"] | order(coalesce(order, 9999) asc, name asc){ \n  _id,\n  name,\n  role,\n  initials,\n  family,\n  track->{ \n  name,\n  \"slug\": slug.current,\n  room,\n  family\n },\n  \"talk\": *[_type == \"session\" && speaker._ref == ^._id] | order(startTime asc)[0].title\n }\n": SPEAKERS_QUERY_RESULT;
    "\n  *[_type == \"session\"] | order(startTime asc, coalesce(order, 9999) asc, title asc){\n    _id,\n    title,\n    kind,\n    startTime,\n    endTime,\n    room,\n    track->{ \n  name,\n  \"slug\": slug.current,\n  room,\n  family\n },\n    speaker->{ name, role }\n  }\n": SESSIONS_QUERY_RESULT;
    "\n  *[_type == \"organizer\"] | order(coalesce(order, 9999) asc, name asc){\n    _id,\n    name,\n    role,\n    initials,\n    family\n  }\n": ORGANIZERS_QUERY_RESULT;
    "\n  *[_type == \"sponsorTier\"] | order(coalesce(order, 9999) asc, name asc){\n    _id,\n    name,\n    kind,\n    headline,\n    description,\n    perks,\n    family,\n    \"sponsors\": *[_type == \"sponsor\" && tier._ref == ^._id]\n      | order(coalesce(order, 9999) asc, name asc){ \n  _id,\n  name,\n  url,\n  logo\n }\n  }\n": SPONSOR_TIERS_QUERY_RESULT;
    "\n  *[_type == \"sponsor\" && tier._ref in *[_type == \"sponsorTier\" && kind == \"paid\"]._id]\n    | order(tier->order asc, coalesce(order, 9999) asc, name asc)[0...4]{ \n  _id,\n  name,\n  url,\n  logo\n }\n": HOME_SPONSORS_QUERY_RESULT;
    "\n  *[_type == \"faq\"] | order(coalesce(order, 9999) asc){\n    _id,\n    question,\n    answer,\n    \"anchor\": anchor.current\n  }\n": FAQ_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

